CREATE TABLE survey (
	question_id INT NOT NULL AUTO_INCREMENT,
	question VARCHAR(255) NOT NULL,
	One INT DEFAULT 0 NOT NULL,
	Two INT DEFAULT 0 NOT NULL,
	Three INT DEFAULT 0 NOT NULL,
	Four INT DEFAULT 0 NOT NULL,
	Five INT DEFAULT 0 NOT NULL,
	CONSTRAINT pk_questionId PRIMARY KEY(question_id)
) ENGINE=InnoDB;