@extends('layouts.default')

@section('content') 
<br> 
<h4>Welcome To NextSemester</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p> 

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p>  

@stop
