@extends('layouts.default')

@section('content') 
<div class="panel radius home-panel"> 
	<h3><strong>Welcome To NextSemester!</strong></h3>
	<br>
	<h4>Our goal with NextSemester is to incorporate an intuitive schedule building app with a social network of fellow classmates.  The idea is to make it easier to create your course schedule in collaboration with friends as well as meet people who are taking classes with you.</h4>
	<br>
	<h4>NextSemester is a tool for pooling resources (youtube videos, helpful websites, and class content) and forming study groups/cram sessions.  Students can set up meet times at the library or alert the rest of the class that you want to work on a specific problem or homework assignment.</h4>
	<br>
	<h4>To get started please sign in or register for a new account.</h4>
</div>
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p> 

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae ligula laoreet mauris feugiat vulputate in sit amet ante. Donec quis ipsum a arcu sollicitudin faucibus non ut orci. Nam pellentesque bibendum blandit. Donec ipsum dolor, suscipit vitae massa ac, scelerisque suscipit dolor. Pellentesque tellus quam, tristique ac congue quis, tristique id turpis. Donec pharetra enim et lectus facilisis, at ullamcorper est feugiat. Cras id sapien eget nisl consequat blandit. Aliquam accumsan hendrerit velit iaculis rutrum. Phasellus vel dolor id est faucibus semper. Nunc at molestie arcu, vel vehicula ex. Nulla id lorem ipsum. Maecenas eu pellentesque leo, id scelerisque ex. Pellentesque vel efficitur augue, at ultrices dolor. Vestibulum ornare consequat lectus eu placerat. </p> 

<p>Nulla lobortis eu libero quis aliquet. Phasellus efficitur quam magna, sed mollis neque elementum et. Aliquam ut consequat turpis. Aliquam vestibulum mi vel mollis pharetra. Morbi odio mauris, dignissim eget commodo in, bibendum id magna. Maecenas interdum felis sagittis, suscipit elit sed, tincidunt eros. In pulvinar efficitur est ut sodales. Suspendisse id maximus augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ligula justo, imperdiet et ligula non, placerat dapibus mauris. Proin varius euismod sapien, sodales scelerisque nunc placerat eu.</p>   -->

@stop
